version: "2"
services:

  redis:
    image: redis:5-alpine
    command: redis-server --save "" --appendonly no
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal_network

  # manager manages the job queue.
  manager:
    image: quay.io/netzbegruenung/green-spider:latest
    command: >
      python3 cli.py
      --credentials-path /secrets/datastore-writer.json
      --loglevel debug manager
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ${PWD}/secrets:/secrets
    depends_on:
      - redis
    networks:
      - internal_network

  rqdashboard:
    image: eoranged/rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379/0
    ports:
      - "9181:9181"
    depends_on:
      - redis
    networks:
      - internal_network

networks:
  internal_network:
    internal: true
